services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AndreasLoewer\SxFavicon\:
    resource: '../Classes/*'

  AndreasLoewer\SxFavicon\Controller\ConfigController:
    public: true        # wichtig für Routing-Auflösung
    tags: ['backend.controller']
